dbhost: leaf-tidb.tidb.svc.cluster.local:4000

ingress:
  annotations:
   nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Cluster-Name: Leaf";
  hosts:
    - host: wordpress-leaf.domains.leaf.cloud
      paths:
        - path: /
          pathType: Prefix
    - host: multi-cluster-demo.com
      paths:
        - path: /
          pathType: Prefix
    - paths:
        - path: /
          pathType: Prefix